NumPyNinja/LMS-Frontend-Phase4

- src/app/assignment/assignment.ts
- src/app/assignment/assignment/assignment.component.html
- src/app/assignment/assignment/assignment.component.ts
Needs to test the flow of Edit and Create assignment.
> Lms 152 -Edit assignment

- src/app/user/user-prog-batch.ts
- src/app/user/user-role-program-batch.ts
- src/app/user/user.service.ts
- src/app/user/user.ts
- src/app/user/user/user.component.html
- src/app/user/user/user.component.ts
> Assigning Program-Batch to User

- src/app/assignment/assignment/assignment.component.html
- src/app/assignment/assignment/assignment.component.ts
> Batch dropdown filtered

- src/app/auth/auth.service.ts
- src/app/dashboard/admindata/admindata.component.html
- src/app/dashboard/admindata/admindata.component.ts
- src/app/dashboard/widgetdata/widgetdata.component.html
> dashboard bugs

- src/app/assignment/assignment.ts
- src/app/assignment/assignment/assignment.component.html
- src/app/assignment/assignment/assignment.component.ts
Hi Jyotsna,
Please review.
thanks 
Bhagya
> LMS-188-Assignment-gradeBy-staffName-populated-dropdown

- src/app/assignment/assignment/assignment.component.html
- src/app/assignment/assignment/assignment.component.ts
Please review. 
Description : Multiple delete button for assignment was not working
> Multiple Assignment delete not working

- src/app/session/session.ts
- src/app/session/session/session.component.html
- src/app/session/session/session.component.ts
Hi Aruna,
I made some changes in those files session.component.html, session.ts, session.compontent .ts and please review.
thanks
Bhagya
> LMS-179-StaffName-populated-in-dropdown

- src/app/user/user/user.component.html
- src/app/user/user/user.component.ts
Hi Aruna, 
Please review.
Description : 
1) In User Edit, after editing and clicking on submit  button, Error loading user details and submit  successfully messages used to come. 
2) After clicking on cancel button, pop up was not getting cancelled.
> User Edit bugs

- src/app/session/session/session.component.html
- src/app/session/session/session.component.ts
Hi Aruna,
please review this code 
Thanks
Bhagya
> LMS-222 classTopic Duplicate validation based on Batch Name in Class Module

- src/app/session/session/session.component.html
- src/app/session/session/session.component.ts
Hi Aruna,
Please review did some changes for front-end validation below files
src/app/session/session/session.component.html and src/app/session/session/session.component.ts.
Thanks
Bhagya
> LMS-192-ClassAddEdit-Frontend-Validation

- src/app/session/session/session.component.html
- src/app/session/session/session.component.ts
Hi Aruna,
please review  multi-class delete code in Class Module.
Thanks
Bhagya
> Lms 217 multiple class delete class module

- src/app/attendance/attendance.ts
- src/app/attendance/attendance/attendance.component.html
- src/app/attendance/attendance/attendance.component.ts
Added new property: attendanceDate
Did necessary changes in view, edit, add, and delete functionalities.
> Updated attendance date

- src/app/assignment/assignment/assignment.component.html
Hi ,
please review this code in Assignment module click--> manage button -->after open the Assignment manage Grade module if table have no record its showing the message "No Record found ".
thanks 
Bhagya
> LMS-213-Assign-Manage-UI-noRecord-message

- src/app/user/user/user.component.html
- src/app/user/user/user.component.ts
Hi shemeeba,
Please review this, you already review this but code conflict so push same code in different branch.
Thanks
Bhagya
> LMS-212-changeUID-to-emailId-basedon-Emailid-roleId-change

- src/app/batch/batch/batch.component.html
- src/app/batch/batch/batch.component.ts
Hi,
please review code for Batch Module validation.
thanks 
Bhagya
> LMS-215-BatchName-unique-validation

- src/app/program/program/program.component.html
- src/app/program/program/program.component.ts
Hi Bhagya,
Please review .
-Priya
> Validation for program component

- src/app/attendance/attendance/attendance.component.html
- src/app/attendance/attendance/attendance.component.ts
Future dates and more than 7 days from the past including the current date are non-editable.
> Attendance dates grey out

- src/app/batch/batch/batch.component.html
- src/app/batch/batch/batch.component.ts
> Should not be able to create a batch out of InAv=ctive Program

- src/app/session/session.service.ts
- src/app/session/session.ts
- src/app/session/session/session.component.html
- src/app/session/session/session.component.ts
Hi Bhagya,
Please review my code.
- Thanks
> Lms 224 class status

- src/app/batch/batch.ts
- src/app/program/program.ts
- src/app/user/user.service.ts
- src/app/user/user.ts
- src/app/user/user/user.component.html
- src/app/user/user/user.component.ts
Hi Aruna,
Please the review code Assign Staff form and Assign Student form.
thanks 
Bhagya
> LMS-41-228-Assign-staff/student-program/batch

- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/user/user/user.component.ts
Hi Aruna,
Please review User Module toolbar.
thanks
Bhagya
> LMS-241-UserModule-Toolbar-dropdown-option

- src/app/assignment/assignment.ts
- src/app/assignment/assignment/assignment.component.ts
- src/app/attendance/attendance/attendance.component.html
- src/app/attendance/attendance/attendance.component.ts
- src/app/batch/batch.ts
- src/app/batch/batch/batch.component.ts
- src/app/session/session.service.ts
- src/app/session/session.ts
- src/app/session/session/session.component.ts
- src/app/user/user.service.ts
Added new field batch name in add attendance
Based on the batch ID class list and user list will populate
In session, assignment, and batch modules, batch id is a string. but in the backend, the batch ID is an Integer. So, I changed the data type to number.
> modified add attendance

- src/app/user/user/user.component.html
- src/app/user/user/user.component.ts
Hi ,
Please review in User Module Assign Staff pop-up change Assign User to Assign Staff.
Thanks
Bhagya
> LMS-251-User-AssignUser-AssignStaffHeader-CosmeticChange

- src/app/assignment/assignment/assignment.component.ts
- src/app/header/header.component.html
- src/app/header/header.component.ts
Hi Shemeeba, 
Please review toolbar menu in Assignment module, it's have only one menu Add New Assignment.
thanks 
Bhagya
> LMS-242-Toolbar-menu-AddNewAssignment

- src/app/attendance/attendance/attendance.component.html
- src/app/attendance/attendance/attendance.component.ts
- src/app/header/header.component.html
- src/app/header/header.component.ts
Please check the new drop-down for add attendance and also please verify add attendance is working properly.
> Toolbar-Dropdown-Option-Attendance

- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/program/program/program.component.ts
Hi Bhagya,
Please review my code.
-Thank you
> added dropdown to program

- src/app/batch/batch.ts
- src/app/batch/batch/batch.component.html
- src/app/batch/batch/batch.component.ts
Hi Shemeeba,
Can you please review Batch validation and layout changes.
Batch Name is combination of program Name and number.
Batch name have tow Input field---- second field only allow number. first field is program name that field is readonly.
Batch name is unique check based on programName and number. 
Thanks 
Bhagya
> LMS-248-249-BatchMoudle-validation-layout

- src/app/user/user/user.component.html
- src/app/user/user/user.component.scss
- src/app/user/user/user.component.ts
Hi Shemeeba,
please review code based on the changes.
First Name, last Name and location – allowed only Alphabet. 
Phone No--- allowed only 10 numbers and regex size="10" pattern="^[1-9]{1}[0-9]{9}.*".
Middle name -- if not null check, its only allowed alphabet.
LinkedIn validation in regex  pattern="^(http(s)?:\/\/)?([\w]+\.)?linkedin\.com\/(pub|in|profile).*"
Required field are:  * 
First Name, last Name, Email, Location, Role Status, Phone no., User Role, User Role Status, User Visa Status, UG, Time Zone.
optional fields are:
Middle name, LinkedIn profile, PG and User Comment.
thanks 
Bhagya
> LMS-254 User Validations

- src/app/assignment/assignment/assignment.component.html
- src/app/assignment/assignment/assignment.component.scss
- src/app/assignment/assignment/assignment.component.ts
Hi Shemeeba,
Please review, I did the code based on following requirements.
Assignment Validation is already there so just adding the asterisk symbol for mandatory field.
Add new field called Class Name, it is mandatory field.
Change Assignment Description field into Class Name field in the Assignment table front-end side.
In Edit Assignment Batch Name is not display in dropdown: fixed it.
thanks
Bhagya
> LMS-267-Add-ClassId-field-addAssignment-LMS-266-assignmentValidation

- src/app/assignment/assignment/assignment.component.html
- src/app/assignment/assignment/assignment.component.scss
- src/app/assignment/assignment/assignment.component.ts
Reverts NumPyNinja/LMS-Frontend-Phase4#62
> Revert "LMS-267-Add-ClassId-field-addAssignment-LMS-266-assignmentValidation"

- src/app/assignment/assignment/assignment.component.html
- src/app/assignment/assignment/assignment.component.scss
- src/app/assignment/assignment/assignment.component.ts
Reverts NumPyNinja/LMS-Frontend-Phase4#63
> Revert "Revert "LMS-267-Add-ClassId-field-addAssignment-LMS-266-assignmentValidation""
